---
- name: install php
  apt:
    name: 
     - php
     - php-pgsql
     - libapache2-mod-php
     - php-curl
     - php-gd
     - php-mbstring
     - php-xml
     - php-xmlrpc
     - php-intl
     - php-zip
    state: latest
    update_cache: yes 
